version: '3'

services:

  # database containers, one for each db
  database1:
    image: postgres
    volumes:
      - database1_volume:/var/lib/postgresql/data
    env_file:
      - config/db/database1_env
    networks:
      - database1_network

  database2:
    image: postgres
    volumes:
      - database2_volume:/var/lib/postgresql/data
    env_file:
      - config/db/database2_env
    networks:
      - database2_network

  # web container, with django + gunicorn
  leadmanagerapp:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE
    volumes:
      - .:/opt/services/leadmanager/src
      - static:/opt/services/leadmanager/src/leadmanager/static
      - media:/opt/services/leadmanager/src/leadmanager/media
    networks:
      - database1_network
      - database2_network
      - nginx_network
    depends_on:
      - database1
      - database2

  # reverse proxy container (nginx)
  nginx:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/opt/services/leadmanager/src/leadmanager/static
      - media:/opt/services/leadmanager/src/leadmanager/media
    networks:
      - nginx_network
    depends_on:
      - leadmanagerapp

networks:
  database1_network:
    driver: bridge
  database2_network:
    driver: bridge
  nginx_network:
    driver: bridge

volumes:
  database1_volume:
  database2_volume:
  static:
  media:
